# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Einzbern Magic Cabal
tagline:             'Blog of Kiritsugu Akitsuki'
description:         'Kiritsugu Akitsuki,a freelancer graduated from Chongqing University,Lisp Develpor.Name in Chinese is Meijie Shen.'
url:                 http://akitsukikiritsugu.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Kiritsugu Akitsuki
  url:               http://akitsukikiritsugu.github.io
  email:             240799357@qq.com

# Custom vars
version:             1.0.0
