# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Azeroth
tagline:             'Blog of ForTheAlliance'
description:         'a boubi graduated from Chongqing University,iOs Develpor.Name in Chinese is Qin Lize.'
url:                 http://ForTheAlliance.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              ForTheAlliance
  url:               http://ForTheAlliance.github.io
  email:             331401931@qq.com

# Custom vars
version:             1.0.0
